export declare const IMGUR_API_PREFIX = "https://api.imgur.com";
export declare const API_VERSION = "3";
export declare const AUTHORIZE_ENDPOINT = "oauth2/authorize";
export declare const ACCOUNT_ENDPOINT: string;
export declare const ALBUM_ENDPOINT: string;
export declare const IMAGE_ENDPOINT: string;
export declare const UPLOAD_ENDPOINT: string;
export declare const GALLERY_ENDPOINT: string;
export declare const SUBREDDIT_GALLERY_ENDPOINT: string;
export declare const SEARCH_GALLERY_ENDPOINT: string;
